### ISSUE TITLE
Add Case Study: Xpanxion

### ISSUE THREAD

**Issue by jcasimir** [turingschool-projects/techhire#10]
On the Tools & Resources page, add the following case study:

“See how [Xpanxion] helped [NAME]” then you click that and a pop-up or drop-down has the individual stories. (if not doable for now just leave out)

Xpanxion is a software engineering firm that provides solutions to businesses through software architecture, design, development, data analytics, and testing services. The company utilizes a unique business model which places offices in rural areas to leverage lower cost structures and bring high tech jobs to smaller communities. However, due to the lower population base, this approach also makes finding qualified talent more difficult in an already competitive and resource constrained industry. Xpanxion as a result has come to an interesting solution – the company invests heavily into training and career development to create its own IT talent pool. Through a rigorous interview process, candidates with strong aptitude and fit are identified and are brought into the organization to begin a regimented training process. This includes those that may not have IT experience, and to date, approximately 35% of Xpanxion’s 250 US employees are of non-traditional  IT backgrounds. The success of the endeavor has led to high growth and expansion of the firm, so Xpanxion looks to partner with the TechHire initiative to leverage the obvious synergies. See how Xpanxion helped Jason and Michael.

Jason Arens

After growing up in the agricultural industry, I earned my bachelor’s degree in Journalism and began a career in sports media. When I decided to pursue a different career path a few years later, I came knocking on Xpanxion’s door with an unrelated background, but the will to learn. I was given the opportunity and haven’t looked back since. Thanks to the company’s in-house training sessions and knowledge transfer from colleagues with expertise, I’ve grown in leaps and bounds through my first year to position myself as a valuable asset for the software services company as a Business and QA Analyst. It was undoubtedly the right move for me, and I look forward to continue growing within this ever-changing industry.

Michael Wortman

I became a member of the Xpanxion Team after spending 21 years in the military in multiple fields and managing a restaurant for over 10 years.  During that time I realized that a lifestyle change was desperately needed.  Working for Xpanxion was that change, and has been one of the most rewarding decisions I could have made.  Previous experience had taught me to mold into whatever the situation called for.  Now I am working throughout several QA teams guiding and assisting in multiple ways.  Xpanxion is fantastic about finding and keeping good people on projects.  They also make sure that almost any tools or resources needed to make you successful are available.  I feel that Xpanxion brought me on as part of their team because they saw my eagerness to be part of a successful team, capacity to grow, self-motivation, and long term dedication.

**Comment by worace** [comment]
https://github.com/turingschool-projects/techhire/pull/33
