### ISSUE TITLE
Tools & Resources Formatting

### ISSUE THREAD

**Issue by jcasimir** [turingschool-projects/techhire#13]
- Fix the text overlap in the "Case for Business" section
- Add “Private Sector Tools” title header under commitments section [more info needed]

**Comment by jcasimir** [comment]
What's the "commitments section"? I'm not sure where this Private Sector Tools is supposed to go on the page.

**Comment by erodrig1010** [comment]
Header order on Tools & Resources page:

The Case for Business (text + calculator)
Case Studies (Xpanxion, Rural Sourcing)
Private Sector Tools (Better Weekdays, Knack, etc)
Fact Sheet

**Comment by erodrig1010** [comment]
If possible, for case studies show the paragraph about the business, and have the individual stories as a drop-down or link so the page isnt so text heavy.

**Comment by worace** [comment]
- [x] Fix text overlap styling
- [x] Add “Private Sector Tools” section
- [x] add Better Weekdays PST example
- [x] add knack PST example
- [x] replace case studies with xpanxion and rural sourcing
- [x] add knack PST example

**Comment by worace** [comment]
closed by https://github.com/turingschool-projects/techhire/pull/33
