### ISSUE TITLE
Revise Sign-Up Email

### ISSUE THREAD

**Issue by jcasimir** [turingschool-projects/techhire#20]
- Reply to should be info@opportunityatwork.org
- Remove any reference to logging in
- Move email sending to a background job
- Check the SendGrid account and keys (and billing)

**Comment by worace** [comment]
closed by https://github.com/turingschool-projects/techhire/pull/29
- verifies signup email working in production via sendgrid and sidekiq
- scaled up 1 sidekiq worker process
- styling / messaging in emails could still probably use work
