### ISSUE TITLE
Content Logins / Administration

### ISSUE THREAD

**Issue by jcasimir** [turingschool-projects/techhire#21]
- Remove the ability to register users through the website
- Debug the problems with loading assets (heroku is running HTTPs, assets are HTTP, Chrome won’t mix modes)

**Comment by worace** [comment]
i think I fixed the second bullet point by switching everything to protocol-relative asset links; it was definitely breaking most of the JS before and now it seems to be working ok.

started working on removing all the user signup stuff

**Comment by worace** [comment]
closed by https://github.com/turingschool-projects/techhire/pull/31
