### ISSUE TITLE
T&R: Cost Calculator

### ISSUE THREAD

**Issue by jcasimir** [turingschool-projects/techhire#26]
Find out How Much Your Open Positions are Costing You
Calculator function
([$434 Cost Per Day] X [# of Open Positions]) X [# of Days Unfilled] = Total Average Cost to Employer
Auto-populate $434, 1, 1 - but allow users to edit all the fields if possible
Cite “CEB Corporate Leadership Council” under the calculator in smaller font
Trust your design judgement which at this point can be very basic

**Comment by worace** [comment]
@jcasimir check this out here: https://techhire-registration.herokuapp.com/tools-resources

**Comment by worace** [comment]
not spectacular but maybe good enough
