### ISSUE TITLE
Front Page: O@W and WH Links

### ISSUE THREAD

**Issue by jcasimir** [turingschool-projects/techhire#27]
From O@W:

> Opportunity@Work 
> 
> Opportunity@Work is a civic enterprise whose mission is to re-wire the U.S. labor market to enable more Americans to achieve upward mobility in the job market and workplace, to facilitate actions by U.S. employers to develop the talent they collectively need to succeed and grow, and to scale up innovations that unlock more fully all people’s potential for higher-value, meaningful work as a source of economic opportunity and national competitive advantage.
> 
> www.opportunityatwork.org
> 
> You can also read more about TechHire by visiting the White House page. 

Where does this go?

**Comment by erodrig1010** [comment]
Bottom of Learn More page. Replace: 

The Opportuntiy@Work Mission

It is our aim to provide the tools, resources, and support to help your organization adopt new recruiting, training, and promotion practices that will result in faster and better hiring and retention.

Find out more about the Tools and Resources Opportunity@Work provides.

**Comment by worace** [comment]
doesn't seem to specify what the "White House page" is; going to link it to here for now -- https://www.whitehouse.gov/issues/technology/techhire

let us know if it needs to change
