### ISSUE TITLE
TOOLS/RESOURCES Page Edits

### ISSUE THREAD

**Issue by erodrig1010** [turingschool-projects/techhire#38]
1. Image next to Xpanxion case study looks like 2 images on top of each other - just keep briefcase image.

**Comment by erodrig1010** [comment]
1. Instead of linking inside the bubble, just add link as the last sentence and make the color of the text red.

ex. ... supply of quality, local talent. [Read more about Xpanxion's training strategy.]

**Comment by erodrig1010** [comment]
1. Add Capital One case study.

If possible as a third column, otherwise centered below Xpanxion and RSI

**Comment by erodrig1010** [comment]
1. Case study page formatting:
- Center logo at top like Xpanxion
- Remove briefcase icon
- Keep check mark icon, but make page white entirely

**Comment by erodrig1010** [comment]
Xpanxion Case Study:
- Last line should read "Read about Xpanxion's training strategy."
- Add "See How Xpanxion Helped Jason and Michael:" to bottom of case studt page with checkmark icon like RSI (white background)

Jason Arens
After growing up in the agricultural industry, I earned my bachelor’s degree in Journalism and began a career in sports media. When I decided to pursue a different career path a few years later, I came knocking on Xpanxion’s door with an unrelated background, but the will to learn. I was given the opportunity and haven’t looked back since. Thanks to the company’s in-house training sessions and knowledge transfer from colleagues with expertise, I’ve grown in leaps and bounds through my first year to position myself as a valuable asset for the software services company as a Business and QA Analyst. It was undoubtedly the right move for me, and I look forward to continue growing within this ever-changing industry.

Michael Wortman
I became a member of the Xpanxion Team after spending 21 years in the military in multiple fields and managing a restaurant for over 10 years.  During that time I realized that a lifestyle change was desperately needed.  Working for Xpanxion was that change, and has been one of the most rewarding decisions I could have made.  Previous experience had taught me to mold into whatever the situation called for.  Now I am working throughout several QA teams guiding and assisting in multiple ways.  Xpanxion is fantastic about finding and keeping good people on projects.  They also make sure that almost any tools or resources needed to make you successful are available.  I feel that Xpanxion brought me on as part of their team because they saw my eagerness to be part of a successful team, capacity to grow, self-motivation, and long term dedication.

**Comment by erodrig1010** [comment]
RSI Case Study:
- Last line "Read about RSI's talent sourcing strategy."

**Comment by erodrig1010** [comment]
Private Sector Tools:
- Use "Private Sector Tools" as the header next to briefcase
- Place 4 logos under this header (Better Weekdays, CEB, Knack, LinkedIn)
- Click the logo to expand content (like when you click "More about Knack)

**Comment by erodrig1010** [comment]
Change background color behind Fact Sheet to the greyish color and make the last part white.

**Comment by worace** [comment]
![tools_resources_page_edits_ _issue__38_ _turingschool-projects_techhire](https://cloud.githubusercontent.com/assets/1227440/7940561/f00461ce-090e-11e5-80f1-1e04eab8e556.png)

@erodrig1010 can you explain what you mean by "the greyish color"? can you include any sort of a sketch or mockup for what you are envisioning here?
