### ISSUE TITLE
Learn More Copy

### ISSUE THREAD

**Issue by erodrig1010** [turingschool-projects/techhire#47]
[TEXT NEXT TO VIDEO - Please make "@" blue throughout]

Beginning with the 21 communities of the TechHire initiative – announced by President Obama in March 2015 – which today represent over 130,000 open IT jobs, Opportunity@Work will work with a range of technology, private sector, and philanthropic partners to create freely available tools to streamline the sign-up and participation of thousands of employers in inclusive hiring, and to facilitate a nationwide learning network to rapidly improve the impact of TechHire. Over 300 employers have already signed on.
The 21 TechHire communities are committed to taking action – working with each other, employers, training institutions, and other partners – to create a better marketplace for IT jobs. TechHire communities – including cities, small states, and rural areas - have announced plans to work together in new ways to recruit and place applicants based on their actual skills and to create more fast track tech training opportunities, based on market-wide hiring needs. TechHire communities will build a talent pipeline by leveraging their 4-year universities and community colleges, but will also leverage non-traditional approaches, including hiring on-ramps for people with the skills but not the pedigree to be hired in traditional ways, accelerated coding “boot camps,” and high-quality online courses that prepare workers for well-paying IT jobs, often in just a few months.
The long-term objective of TechHire is to create the labor market conditions nationally that enable employers to "hire when ready" and job seekers to be aware of, prepare for, and connect with IT jobs and careers. By creating compelling proof points in communities throughout the country; uncovering common challenges; developing scalable solutions; and bringing to bear national and regional partnerships and resources, TechHire, with support from Opportunity@Work, will serve as a catalyst to transforming the broader labor market.

**Comment by erodrig1010** [comment]
Change "The Opportunity: Rethinking the Skills Gap" to "Rethinking the “Skills Gap” as a Labor Market Failure: Need and the Opportunity"

With over 5 million open jobs in the United States—the highest level in at least 15 years—how can so many American workers find themselves stuck, without a path to well-paid employment? Nearly half of U.S. employers report difficulty in hiring employees who have the skills their companies need to compete, a figure consistent with employer surveys over the last two business cycles. Yet, since 2000, real wages for the median worker have stagnated and voluntary job changes – i.e., quitting a job to take or seek a better (usually higher-paying) one – are down by 28 percent.  This seems like a confounding paradox, but a few U.S. statistics offer some clues as to the underlying causes:

**Comment by erodrig1010** [comment]
U.S. Job Openings by the Numbers
1.  While only 19 percent of administrative assistants have four-year college degrees, 65 percent of new assistant job postings require a four-year degree just to be considered. (Burning Glass) 
2.  Employers are only half as likely to grant an interview to a job candidate unemployed for over 6 months, compared to someone more recently employed with identical education, skills and experience. Yet, a study of 20,000 hires found that this distinction made no difference in likely job performance. (Evolv)
3.  Less educated workers report being only half as likely to receive valuable on-the-job training from their employers as did workers with more formal education. (OECD)

**Comment by erodrig1010** [comment]
Underlying Issues

What these dysfunctions all have in common is an origin on the “demand” side of the U.S. labor market – how employers recruit, hire, train, and promote.  Yet most interventions that aim to improve employment outcomes focus purely on the “supply side”— education and job training. These efforts are important, but they can’t “close the skills gap” without demand-side reforms. We need smarter, more inclusive employer practices and the partnerships and public policies to support them. Employers are experiencing a classic market failure, in which screening, hiring, and training practices are inadvertently limiting the collective talent pipeline and creating “skills mismatches” with economy-wide ripple effects. As an illustration of how costly this is for employers, consider the following back-of-the-envelope estimate. An open job costs $434 each day in lost productivity and sales (CEB) – considerably more in high-value fields such as IT, where jobs pay 76 percent above average (BLS). The average time to fill an open IT job nearly doubled from 43 to 76 days in the past 5 years.   With nearly 600,000 open IT jobs now – just 12 percent of total open jobs – and a million more projected in the next few years, just shrinking average time-to-fill IT jobs back to 2010 levels is worth around $40 billion annually to US employers: double what’s spent on all federal job training programs.

**Comment by worace** [comment]
@erodrig1010 i put these in but the new copy for "Underlying Issues" makes it a good bit longer than the left side of that section ("Job openings by the numbers"). You'll have to look and see if you want to shorten it some.
