### ISSUE TITLE
Manage Static Content

### ISSUE THREAD

**Issue by Tmee** [turingschool-projects/techhire#60]
-table width not correct

-switch order of content to have most recently updated content on the top of the table

-page and slot attributes on Content do not seem to used at the moment
       -is this how the admin will be able to choose which page and where on the page static content will             go?

**Comment by AllPurposeName** [comment]
-edit and delete functionality

**Comment by AllPurposeName** [comment]
-some way to view individual Content. The body/description is limited to under 17 characters

**Comment by Tmee** [comment]
All are done except the bit about page and slot attributes on Contact.  Need more info on them.

**Comment by Tmee** [comment]
table styling fixed. order fixed, but with locations. page and slot attributes removed. edit functionality added, delete function removed.  Show for static content implemented.
