### ISSUE TITLE
Replace Header Image

### ISSUE THREAD

**Issue by jcasimir** [turingschool-projects/techhire#9]
We need to create a replacement for https://github.com/turingschool-projects/techhire/blob/master/app/assets/images/bg_hero.jpg using our images.

**Comment by jcasimir** [comment]
Turing photos: https://www.dropbox.com/sh/efqofshh3tfe5r3/AACvppOfj8MowH2txMtaM1fwa?dl=0

**Comment by worace** [comment]
https://github.com/turingschool-projects/techhire/pull/33
